name: Lint con LanguageTool + Reviewdog

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.txt'
  push:
    paths:
      - '**/*.md'
      - '**/*.txt'

jobs:
  languagetool:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar Reviewdog
      run: |
        curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh

    - name: Lint con LanguageTool usando Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace \
          silviof/docker-languagetool \
          --language es --enable all /workspace/**/*.md /workspace/**/*.txt \
          --json \
        | reviewdog -f=golint -name="LanguageTool" -reporter=github-pr-review -level=error
