name: Revisar ortografía y gramática

on:
  push:
    branches:
      - '**'  # Se ejecuta en cualquier rama
  pull_request:

jobs:
  check_text:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Ejecutar LanguageTool con Reviewdog
      uses: reviewdog/action-languagetool@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-check  # Se ve como check en GitHub
        level: error
        language: es
        enabledRules: ALL   # Habilita todas las reglas, incl. ortografía
        patterns: |
          **/*.md
          **/*.txt
