name: Lint con LanguageTool

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.txt'
  push:
    paths:
      - '**/*.md'
      - '**/*.txt'

jobs:
  languagetool:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Ejecutar LanguageTool con Reviewdog
        uses: reviewdog/action-languagetool@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          language: es
          patterns: |
            **/*.md
            **/*.txt
