name: LanguageTool Check via Reviewdog

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  languagetool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run LanguageTool with reviewdog
        uses: reviewdog/action-languagetool@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: info
          patterns: "**/*.md **/*.txt"
          language: es
