name: Revisión de texto estricta

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  spell_and_grammar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      # --- Ortografía ---
      - name: Revisar ortografía con Misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error        # cualquier error hace que falle el check
          fail_on_error: true # fuerza fallo si hay errores
          locale: es
          patterns: "**/*.md\n**/*.txt"

      # --- Gramática y estilo ---
      - name: Revisar gramática con LanguageTool
        uses: reviewdog/action-languagetool@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error         # cualquier error hace que falle el check
          fail_on_error: true  # fuerza fallo si hay errores
          language: es
          enabledRules: ALL
          patterns: "**/*.md\n**/*.txt"
